"""empty message

Revision ID: 360794956c86
Revises: 00e95a0dbca6
Create Date: 2019-11-29 17:54:44.043931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '360794956c86'
down_revision = '00e95a0dbca6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
